//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string RealName { get; set; }
        public byte Age { get; set; }
        public bool Sex { get; set; }
        public string Mobile { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
    }
}
