//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.userCard = new HashSet<userCard>();
        }
    
        public int userId { get; set; }
        public string userName { get; set; }
        public string realName { get; set; }
        public int age { get; set; }
        public string telPhone { get; set; }
        public System.DateTime createDate { get; set; }
    
        public virtual ICollection<userCard> userCard { get; set; }
    }
}
